For testing samFilter
Set up directories
  $ CURDIR=$TESTDIR
  $ REMOTEDIR=/mnt/secondary-siv/secondarytest/testdata/BlasrTestData/ctest
  $ DATDIR=$REMOTEDIR/data
  $ OUTDIR=$CURDIR/out
  $ STDDIR=$REMOTEDIR/stdout

Set up the executable: samFilter.
  $ BIN=$TESTDIR/../pbihdfutils/bin/
  $ EXEC=$BIN/samFilter

#Test samFilter with a *.sam file generated by blasr
  $ OUTFILE=$OUTDIR/lambda_bax_filter_1.sam
  $ STDFILE=$STDDIR/lambda_bax_filter_1.sam

  $ rm -f $OUTFILE
  $ $EXEC $DATDIR/lambda_bax.sam $DATDIR/lambda_ref.fasta $OUTFILE -minAccuracy 70 -minPctSimilarity 30 -hitPolicy all
  $ tail -n+7 $OUTFILE | md5sum 
  1280157f8e9cf1a133684807419b9360  -

#Test samFilter with -hitPolicy allbest
  $ OUTFILE=$OUTDIR/lambda_bax_filter_2.sam
  $ STDFILE=$STDDIR/lambda_bax_filter_2.sam

  $ rm -f $OUTFILE
  $ $EXEC $DATDIR/lambda_bax.sam $DATDIR/lambda_ref.fasta $OUTFILE -hitPolicy allbest
  $ tail -n+7 $OUTFILE | md5sum 
  46c45c202ad170f9d04951bbf95fc62a  -

#Test samFilter with -hitPolicy random   
  $ OUTFILE=$OUTDIR/lambda_bax_filter_3.sam
  $ STDFILE=$STDDIR/lambda_bax_filter_3.sam

  $ rm -f $OUTFILE
  $ $EXEC $DATDIR/lambda_bax.sam $DATDIR/lambda_ref.fasta $OUTFILE -hitPolicy random
  $ tail -n+7 $OUTFILE | md5sum 
  e8668ee48fde6eb27cf786cc4ba5bb6d  -

#Test samFilter with -hitPolicy randombest   
  $ OUTFILE=$OUTDIR/lambda_bax_filter_4.sam
  $ STDFILE=$STDDIR/lambda_bax_filter_4.sam

  $ rm -f $OUTFILE
  $ $EXEC $DATDIR/lambda_bax.sam $DATDIR/lambda_ref.fasta $OUTFILE -hitPolicy randombest 
  $ tail -n+7 $OUTFILE | md5sum 
  46c45c202ad170f9d04951bbf95fc62a  -


#Test samFilter with -scoreFunction 
  $ OUTFILE=$OUTDIR/lambda_bax_filter_5.sam
  $ STDFILE=$STDDIR/lambda_bax_filter_5.sam

  $ rm -f $OUTFILE
  $ $EXEC $DATDIR/lambda_bax.sam $DATDIR/lambda_ref.fasta $OUTFILE -scoreFunction alignerscore
  $ tail -n+7 $OUTFILE | md5sum 
  46c45c202ad170f9d04951bbf95fc62a  -

#Test samFilter with -holeNumbers
  $ OUTFILE=$OUTDIR/lambda_bax_filter_6.sam
  $ STDFILE=$STDDIR/lambda_bax_filter_6.sam

  $ rm -f $OUTFILE
  $ $EXEC $DATDIR/lambda_bax.sam $DATDIR/lambda_ref.fasta $OUTFILE -holeNumbers 101350-105000,21494 
  $ tail -n+7 $OUTFILE | md5sum 
  46c45c202ad170f9d04951bbf95fc62a  -



